openapi: 3.0.2
info:
  version: 1.0.0
  title: Business Travel Alerts API
  termsOfService: 'https://alert.starliner.ru'
  contact:
    email: info@starliner.ru
    url: 'https://alert.starliner.ru'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://alert.starliner.ru/themes/Coronavirus/assets/images/logos/logo-192.png'
  description: >
    Business Travel Alerts API
tags:
  - name: Airports
    description: Сервисы API по аэропортам
components:
  schemas:
    Airport:
      $ref: /components/schemas/Airport.yaml
servers:
  - url: 'https://alert.starliner.ru/api/v1'
    description: Production server
  - url: 'https://alert-test.starliner.ru/api/v1'
    description: Staging server
paths:
  /geography/airports/{iataCode}:
    $ref: paths/airportByIataCode.yaml
  /geography/airports/{iataCode}/news:
    $ref: paths/airportNewsByIataCode.yaml