openapi: 3.0.2
info:
  version: 1.0.0
  title: Business Travel Alerts API
  termsOfService: 'https://alert.starliner.ru'
  contact:
    email: info@starliner.ru
    url: 'https://www.starliner.ru'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://alert.starliner.ru/themes/Coronavirus/assets/images/logos/logo-192.png'
  description: >
    Business Travel Alerts API
servers:
  - url: 'httpы://alert.starliner.ru/api/v1'
  - url: 'httpы://alert-test.starliner.ru/api/v1'
paths:
  /geography/airports/{iataCode}:
    $ref: paths/airports.yaml